ALTER TABLE challenges
  ADD COLUMN IF NOT EXISTS winner_recipe_id INT UNSIGNED   DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS winner_username  VARCHAR(80)    DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS winner_title     VARCHAR(255)   DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS winner_image_url LONGTEXT       DEFAULT NULL;
