ALTER TABLE challenges ADD COLUMN winner_recipe_id INT UNSIGNED DEFAULT NULL;
ALTER TABLE challenges ADD COLUMN winner_username VARCHAR(80) DEFAULT NULL;
ALTER TABLE challenges ADD COLUMN winner_title VARCHAR(255) DEFAULT NULL;
ALTER TABLE challenges ADD COLUMN winner_image_url LONGTEXT DEFAULT NULL;
